sudo: required
dist: trusty
language: generic
env:
  - ROS_DISTRO=indigo
  - ROS_DISTRO=jade
matrix:
  allow_failures:
    - env: ROS_DISTRO=jade
# Install system dependencies, namely ROS.
before_install:
  # Define some config vars.
  - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. [precise|trusty]
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - export ROS_PARALLEL_JOBS='-j8 -l6'
  # Install ROS
  - sudo sh -c "echo \"deb http://packages.ros.org/ros-shadow-fixed/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  # Install ROS
  - sudo apt-get install -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Setup for rosdep
  - sudo rosdep init
  - rosdep update

# Create a catkin workspace with the package under test.
install:
  - mkdir -p ~/catkin_ws/src

  # Add the package under test to the workspace.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace

# Install all dependencies, using wstool and rosdep.
# wstool looks for a ROSINSTALL_FILE defined in before_install.
before_script:
  # source dependencies: install using wstool.
  - cd ~/catkin_ws/src
  - wstool init

  # package depdencies: install using rosdep.
  - cd ~/catkin_ws
  - rosdep install -y -q --from-paths src --ignore-src --rosdistro $ROS_DISTRO

# Compile and test.
script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin_make_isolated
  - rm -fr build* devel* install*
  - (cd src/openrave_planning; git clean -xfd)
  - catkin_make_isolated --install

after_failure:
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done
