# goal
int32 id
openrave_msgs/TaskParameters task
openrave_msgs/EnvOptimizationParameters envoptimization
---
# result
openrave_msgs/EnvOptimizationResults res
float32 timeelapsed
---
# feedback
openrave_msgs/EnvOptimizationResults res
int32 workcomplete
int32 totalwork
